server:
  port: 8010
spring:
  application:
    name: descovery-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    hostname: localhost

